name: Auto Deploy to GoDaddy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: aicloudetools.com
          username: kpbisslzozf2
          password: Akashya@12
          port: 21
          protocol: ftp
          server-dir: /public_html/